### ISSUE TITLE
프로젝트 파악 및 grpc로 

### ISSUE THREAD

**Issue by kaestro** [tldr-development/fiber-grpc#12]
- [ ] grpc 기초적인 학습하고, 이거통해서 뭘 만들수 있는지 고민한 뒤에
- [ ] sample.proto 수정하고 grpc.pb.go 변경되는 것 확인하기
- [ ] 기초적인 기능 추가해보고
- [ ] 네가 작성한 테스트 코드 읽고, 코드리뷰 날리고 리팩토링

**Comment by hojin-kr** [comment]
sample-server의 테스트에 GCP 인프라에 대한 사용이 포함되어 있어, GCP의 인증키가 있어야 테스팅이 가능함 , 
datstore와 CloudStorage의 사용이 로컬환경에 구성하기 곤란하기 때문에 클라우드에 직접 데브 환경 구성을 사용하여 테스팅함

**Comment by hojin-kr** [comment]
키는 보안성이 있어서 요청하면 별도로 다음과 같은 형태로 전달 해줄 예정
```
export G_PRIVATE_KEY_B64=xxx
export GCP_PROJECT_ID=xxx
export G_ACCESS_IDxxx
```
